language: go
go:
- tip
addons:
    code_climate:
        repo_token: f40020d784d363f5316dc7fd7eb7032d561a427e791744ccad8a0ad39c0edb1e
before_script:
- mkdir build
- cd build
script:
- go build core/game.go
