language: go
addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - xorg-dev
sudo: false
go:
- tip
addons:
    code_climate:
        repo_token: f40020d784d363f5316dc7fd7eb7032d561a427e791744ccad8a0ad39c0edb1e
install:
- go get -u github.com/go-gl/glfw/v3.1/glfw
- go get -u github.com/go-gl/gl
script:
- go build *.go
