sudo: false
addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev
language: go
go:
- tip
install:
- go get -u github.com/go-gl/glfw/v3.1/glfw
- go get -u github.com/go-gl/gl
script:
- go build *.go
