language: cpp
compiler:
- gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- pip install --user cpp-coveralls
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -O0 --coverage" -DCMAKE_BUILD_TYPE=Debug ..
script:
- make
after_success:
- cd ..
- coveralls --exclude build --gcov-options '\-lp'
